# Site metadata and configuration

# Greeting message - optional
greeting: Hello! I am

# Your information
first_name: You
middle_name: R.
last_name: Name
nickname: YRN

# Your image
icon: ☢️ # /assets/icon.jpg

# Contact information
contacts:
  - url: mailto:you@example.com
    icon: fa-solid fa-envelope
  - url: /
    icon: fa-brands fa-github
  - url: /
    icon: fa-brands fa-linkedin
  - url: /
    icon: fa-brands fa-x-twitter
  - url: /
    icon: fa-brands fa-medium
  - url: /
    icon: fa-brands fa-google-scholar

# Site configuration
url: https://iam-tsr.github.io
baseurl: /tsr-page # leave empty for github action deployment
width: 900px

# Pages configuration
pages:
  - title: about
    url: / # use '/' for root page
    page: _content/about.html
    css: /_style/about.css
    content: content/about
    metadata: metadata/about.yml

  - title: projects
    caption: Here are some of my projects.
    url: /projects/
    page: _content/projects.html
    css: /_style/projects.css
    metadata: metadata/projects.yml

  - title: publications
    caption: Here are some of my publications.
    url: /publications/
    page: _content/publications.html
    css: /_style/publications.css
    metadata: metadata/publications.yml

  - title: blog
    caption: Here are my thoughts and writings on various topics.
    url: /blog/
    page: _content/blog.html
    css: /_style/blog.css
    content: content/blog
    metadata: metadata/blog.yml